name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies from both requirements.txt files
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r app/requirements.txt

      # Run tests with pytest
      - name: Run tests
        run: |
          export PYTHONPATH=.
          python3 tests/test.py

      # Run linting with pylint
      - name: Run pylint
        run: |
          pylint app/ || exit 0 # Allow linting to fail without failing the pipeline

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t commonassessmenttool .

      # Run Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name app-container commonassessmenttool
